### ISSUE TITLE
[Bug] False positives for handle object opAssign, null into ? argument

### ISSUE THREAD

**Issue by etherealcardinal** [sashi0034/angel-lsp#361]
Hi, thanks for fixing the bug in my last issue! I've found two other false positives that were introduced after that update.

Example code with highlighted errors:
<img width="681" height="261" alt="Image" src="https://github.com/user-attachments/assets/4aeb788f-5e83-48b4-915d-b98b37548ceb" />

Specific error descriptions:
<img width="587" height="69" alt="Image" src="https://github.com/user-attachments/assets/3d029868-6936-4113-86ac-f54450850397" />

Copy-paste code:
```cpp
// Declaration (as.predefined)
void use_any(?&out);

// Implementation
class test_class { }

void bugs(const test_class&in const_b, test_class&in b)
{
    // BUG 1: cannot copy from a const reference (works in both v0.3.87 and v0.3.95)
    test_class@ a_works = b;
    test_class@ a_fails = const_b;
    a_works = b;
    a_fails = const_b;

    // BUG 2: cannot pass null into a ? argument (works in v0.3.87)
    use_any(null);
}
```

Engine doesn't report compilation errors for the provided snippet. When passing null to any argument, app receives asTYPEID_VOID and decides to throw or ignore.
